"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarDays,Users,Scissors,Clock3,LogOut,CheckCircle2,XCircle,LayoutDashboard} from "lucide-react";
import {supabaseBrowser} from "@/lib/supabase";
type Appointment={id:string;appointment_date:string;start_time:string;end_time:string;status:string;customers?:{full_name:string;phone:string}|null;services?:{name:string}|null};
const labels:Record<string,string>={pending:"در انتظار",confirmed:"تأیید شده",cancelled:"لغو شده",completed:"انجام شده"};
export default function Admin(){
 const sb=useMemo(()=>supabaseBrowser(),[]),[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[appointments,setAppointments]=useState<Appointment[]>([]),[services,setServices]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[tab,setTab]=useState("dashboard");
 useEffect(()=>{sb.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[sb]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const {error}=await sb.auth.signInWithPassword({email,password});if(error)setError("ایمیل یا رمز عبور صحیح نیست.");setBusy(false)}
 async function load(){const [a,s,c]=await Promise.all([sb.from("appointments").select("id,appointment_date,start_time,end_time,status,customers(full_name,phone),services(name)").order("appointment_date").order("start_time"),sb.from("services").select("*").order("created_at",{ascending:false}),sb.from("customers").select("*").order("created_at",{ascending:false})]);if(!a.error)setAppointments((a.data as any)||[]);if(!s.error)setServices(s.data||[]);if(!c.error)setCustomers(c.data||[])}
 useEffect(()=>{if(session)load()},[session]);
 async function status(id:string,status:string){await sb.from("appointments").update({status}).eq("id",id);load()}
 if(loading)return <div className="center">در حال بارگذاری…</div>;
 if(!session)return <main className="login"><div className="login-card"><div className="brand-mark">ES</div><p className="eyebrow">ELHAM SARABI</p><h1>ورود به پنل مدیریت</h1><p className="muted">مدیریت نوبت‌ها، مشتریان و خدمات</p><form onSubmit={login}><label>ایمیل<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>رمز عبور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?"در حال ورود…":"ورود"}</button></form></div></main>;
 const pending=appointments.filter(x=>x.status==="pending").length,confirmed=appointments.filter(x=>x.status==="confirmed").length;
 return <div className="shell"><aside><div className="brand"><div className="brand-mark">ES</div><div><b>Elham Sarabi</b><span>پنل مدیریت</span></div></div><nav>{[["dashboard","داشبورد",LayoutDashboard],["appointments","نوبت‌ها",CalendarDays],["customers","مشتریان",Users],["services","خدمات",Scissors]].map(([id,label,I]:any)=><button className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)} key={id}><I size={19}/>{label}</button>)}</nav><button className="logout" onClick={()=>sb.auth.signOut()}><LogOut size={18}/>خروج</button></aside><main className="content"><header><div><p className="eyebrow">مدیریت سالن</p><h1>{tab==="dashboard"?"داشبورد":tab==="appointments"?"نوبت‌ها":tab==="customers"?"مشتریان":"خدمات"}</h1></div><div className="user">{session.user.email}</div></header>{tab==="dashboard"&&<><section className="cards"><div className="card"><span>نوبت‌های در انتظار</span><strong>{pending}</strong><Clock3/></div><div className="card"><span>نوبت‌های تأییدشده</span><strong>{confirmed}</strong><CheckCircle2/></div><div className="card"><span>مشتریان</span><strong>{customers.length}</strong><Users/></div><div className="card"><span>خدمات فعال</span><strong>{services.filter(x=>x.is_active).length}</strong><Scissors/></div></section><section className="panel"><div className="panel-head"><h2>نوبت‌های اخیر</h2><button onClick={()=>setTab("appointments")}>مشاهده همه</button></div><AppointmentList items={appointments.slice(0,8)} onStatus={status}/></section></>}{tab==="appointments"&&<section className="panel"><div className="panel-head"><h2>همه نوبت‌ها</h2></div><AppointmentList items={appointments} onStatus={status}/></section>}{tab==="customers"&&<section className="panel"><div className="panel-head"><h2>لیست مشتریان</h2></div><div className="table">{customers.map(c=><div className="row" key={c.id}><div><b>{c.full_name}</b><span>{c.phone}</span></div><span>{new Date(c.created_at).toLocaleDateString("fa-IR")}</span></div>)}{!customers.length&&<Empty text="هنوز مشتری‌ای ثبت نشده است."/>}</div></section>}{tab==="services"&&<section className="panel"><div className="panel-head"><h2>خدمات</h2></div><div className="table">{services.map(s=><div className="row" key={s.id}><div><b>{s.name}</b><span>{s.duration_minutes} دقیقه</span></div><span className={s.is_active?"pill ok":"pill"}>{s.is_active?"فعال":"غیرفعال"}</span></div>)}{!services.length&&<Empty text="خدمتی ثبت نشده است."/>}</div></section>}</main></div>}
function AppointmentList({items,onStatus}:{items:Appointment[];onStatus:(id:string,status:string)=>void}){return <div className="table">{items.map(a=><div className="row appointment" key={a.id}><div><b>{a.customers?.full_name||"مشتری"}</b><span>{a.services?.name||"—"} · {a.start_time.slice(0,5)} تا {a.end_time.slice(0,5)}</span></div><div className="date">{new Date(a.appointment_date+"T12:00:00").toLocaleDateString("fa-IR",{weekday:"short",month:"short",day:"numeric"})}</div><div className="actions"><span className={"pill "+a.status}>{labels[a.status]||a.status}</span>{a.status==="pending"&&<><button onClick={()=>onStatus(a.id,"confirmed")}><CheckCircle2 size={18}/></button><button onClick={()=>onStatus(a.id,"cancelled")}><XCircle size={18}/></button></>}</div></div>)}{!items.length&&<Empty text="نوبتی ثبت نشده است."/>}</div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
